// Curated import of the legacy fortuneelectrical.com project library.
//
// CONTENT RULE: every value below comes from the legacy site's own text
// (project descriptions, "Location / CM / Owner / Approximate Amount" lines,
// or image filenames). Nothing is invented. Unknown values are left out.
// `review` notes flag anything that was inferred and should be confirmed.

export const categories = [
  { slug: "aviation", name: "Aviation", sort_order: 1 },
  { slug: "multifamily", name: "Multifamily", sort_order: 2 },
  { slug: "senior-living", name: "Senior Living & Healthcare", short_name: "Senior Living", sort_order: 3 },
  { slug: "education", name: "Education", sort_order: 4 },
  { slug: "government", name: "Government & Public Safety", short_name: "Government", sort_order: 5 },
  { slug: "commercial", name: "Commercial & Retail", short_name: "Commercial", sort_order: 6 },
  { slug: "hospitality", name: "Hospitality & Marine", short_name: "Hospitality", sort_order: 7 },
  { slug: "community", name: "Community & Recreation", short_name: "Community", sort_order: 8 },
  { slug: "power", name: "Power & Energy", sort_order: 9 },
];

// legacy: WordPress slug on the old site (used to pull images)
export const projects = [
  // ------------------------------------------------------------------ current
  {
    legacy: "rsw-airport-terminal-expansion",
    slug: "rsw-airport-terminal-expansion",
    name: "RSW Airport Terminal Expansion",
    status: "current",
    category: "aviation",
    city: "Fort Myers",
    summary: "A $331M terminal expansion at Southwest Florida International Airport, consolidating TSA screening into a new 16-lane checkpoint.",
    description: [
      "The $331-million project improves the airport's efficiency by consolidating and streamlining security checkpoints, adding concession space and giving passengers more amenities and options.",
      "Transportation Security Administration checkpoints are consolidated into a new 16-lane configuration, with additional seating, concession space and a business lounge. In total, more than 164,000 square feet of space is remodeled and 117,000 square feet of new walkways and concession space is added to the terminal.",
    ],
    project_value: 331000000,
    square_feet: 281000,
    project_size: "164,000 SF remodeled + 117,000 SF new",
    general_contractor: "Manhattan Construction (Florida)",
    owner: "Lee County Port Authority",
    architect: "Atkins North America, Inc.",
    featured: true,
    display_order: 1,
    review: "Owner taken from the Lee County Port Authority logo listed under 'Current Commercial Projects'. Square feet = 164,000 remodeled + 117,000 new.",
  },

  // --------------------------------------------------------- recent / verify
  {
    legacy: "the-hadley",
    slug: "the-hadley",
    name: "The Hadley",
    status: "completed",
    category: "multifamily",
    city: "Cape Coral",
    summary: "A 444-unit apartment community between Pine Island Road and Embers Parkway.",
    description: [
      "444-unit apartment complex a block east of Chiquita Boulevard, about halfway between Pine Island Road and Embers Parkway.",
    ],
    units: 444,
    display_order: 10,
    review: "Status unknown. City inferred from the street description (Chiquita / Pine Island Rd / Embers Pkwy).",
  },
  {
    legacy: "silver-hills-at-fort-myers",
    slug: "silver-hills-at-fort-myers",
    name: "Silver Hills at Fort Myers",
    status: "completed",
    category: "multifamily",
    city: "Fort Myers",
    summary: "Two-building, 327-unit luxury riverfront community (Triton Cay) with a 580-space parking garage.",
    description: [
      "Silver Hills at Fort Myers, marketed to residents as Triton Cay, is a two-building, four-to-five-story luxury apartment community at 2220 West First Street and 1901 Altamont Avenue, built in two phases on a 4.46-acre parcel along the Caloosahatchee River.",
      "The two buildings contain 327 apartments — studio, one-, two- and three-bedroom units — with a 580-space parking garage located mid-block between them.",
    ],
    units: 327,
    project_size: "2 buildings · 4–5 stories · 580-space garage",
    display_order: 11,
    review: "Status unknown.",
  },
  {
    legacy: "silver-hills-universal",
    slug: "silver-hills-universal",
    name: "Silver Hills – Universal",
    status: "completed",
    category: "multifamily",
    city: "Orlando",
    summary: "Four-story, 346-unit wrap apartment community with a 426-space parking garage next to Universal.",
    description: [
      "Silver Hills at Universal is a four-story wrap-around 346-unit apartment complex with a 426-space parking garage, located next to the Universal resorts.",
    ],
    units: 346,
    stories: 4,
    project_size: "Wrap product · 426-space garage",
    display_order: 12,
    review: "Status unknown. City inferred from 'next to Universal resorts'.",
  },
  {
    legacy: "magnolia-pond-apartments",
    slug: "magnolia-pond-apartments",
    name: "Magnolia Pond Apartments",
    status: "completed",
    category: "multifamily",
    summary: "432 units across 12 three-story residential buildings, plus clubhouse, maintenance building and site amenities.",
    description: [
      "The project features 12 three-story residential apartment buildings, a one-story clubhouse and a one-story maintenance building.",
      "Site structures include trash compactor enclosures, recreational areas, a pickleball court, putting green and dog park.",
    ],
    units: 432,
    square_feet: 175093,
    stories: 3,
    project_size: "12 residential buildings + clubhouse",
    display_order: 13,
    review: "Status and city unknown.",
  },
  {
    legacy: "altis-santa-barbara",
    slug: "altis-santa-barbara",
    name: "Altis Santa Barbara",
    status: "completed",
    category: "multifamily",
    summary: "An upscale 242-apartment community with more than 160,000 SF of new construction.",
    description: [
      "More than 160,000 square feet of new construction delivering 242 apartments in one- to three-bedroom layouts. Some homes include private entryways, garage access and elevators.",
      "Amenities include a fitness center with yoga studio and wellness room, a gated dog park, cyber café, movie theater, game room and conference center.",
    ],
    units: 242,
    square_feet: 160000,
    display_order: 14,
    review: "Status and city unknown. Square feet is stated as 'more than 160,000'.",
  },
  {
    legacy: "canopy-at-babcock-ranch",
    slug: "canopy-at-babcock-ranch",
    name: "Canopy at Babcock Ranch",
    status: "completed",
    category: "multifamily",
    city: "Babcock Ranch",
    summary: "Studio through three-bedroom apartment homes in Babcock Ranch, the solar-powered town.",
    description: [
      "Studio, one-, two- and three-bedroom apartment homes in Babcock Ranch — a community that generates its own power.",
    ],
    display_order: 15,
    review: "Status unknown.",
  },
  {
    legacy: "center-place-fort-myers",
    slug: "center-place-fort-myers",
    name: "Center Place Fort Myers",
    status: "completed",
    category: "multifamily",
    city: "Fort Myers",
    display_order: 16,
    review: "Status and category unknown (no description on legacy site).",
  },
  {
    legacy: "fort-myers-town-village-walk",
    slug: "fort-myers-town-village-walk",
    name: "Fort Myers Town Village Walk",
    status: "completed",
    category: "multifamily",
    city: "Fort Myers",
    display_order: 17,
    review: "Status and category unknown (no description on legacy site).",
  },
  {
    legacy: "charlotte-county-airport-rescue-and-fire-fighter-training-simulator-facility",
    slug: "charlotte-county-airport-arff-training-facility",
    name: "Charlotte County Airport Rescue & Fire Fighter Training Simulator Facility",
    status: "completed",
    category: "aviation",
    location_label: "Charlotte County, FL",
    summary: "Aircraft rescue and firefighting (ARFF) training simulator facility at Charlotte County Airport.",
    display_order: 18,
    review: "Status unknown.",
  },
  {
    legacy: "naples-botanical-garden-evenstad-horticultural-campus",
    slug: "naples-botanical-garden-evenstad-horticultural-campus",
    name: "Naples Botanical Garden — Evenstad Horticultural Campus",
    status: "completed",
    category: "community",
    city: "Naples",
    summary: "A $15.5M growing and research facility supporting the Garden's plant science and conservation programs.",
    description: [
      "The Evenstad Horticulture Campus is a $15.5 million growing facility that supports the Garden's development of nature-based environmental solutions, expands its collections of tropical and subtropical plants, and enhances its 170 acres of cultivated gardens and native habitat.",
      "The campus moves the Garden into its next phase as a regional resource for plant science, conservation and education.",
    ],
    project_value: 15500000,
    display_order: 19,
    review: "Status unknown.",
  },
  {
    legacy: "fgcu-ab9-the-water-school",
    slug: "fgcu-ab9-the-water-school",
    name: "FGCU AB9 — The Water School",
    status: "completed",
    category: "education",
    city: "Fort Myers",
    display_order: 20,
    review: "Status unknown (no description on legacy site).",
  },
  {
    legacy: "collier-county-sports-complex",
    slug: "collier-county-sports-complex",
    name: "Collier County Sports Complex",
    status: "completed",
    category: "community",
    city: "Naples",
    display_order: 21,
    review: "Status unknown (no description on legacy site).",
  },
  {
    legacy: "babcock-neighborhood-school",
    slug: "babcock-neighborhood-school",
    name: "Babcock Neighborhood School",
    status: "completed",
    category: "education",
    city: "Babcock Ranch",
    display_order: 22,
    review: "Status unknown (no description on legacy site).",
  },

  // ---------------------------------------------------------- completed (legacy)
  {
    legacy: "island-coast-high-school",
    slug: "island-coast-high-school",
    name: "Island Coast High School",
    status: "completed",
    category: "education",
    city: "Cape Coral",
    summary: "Three-story, 291,345 SF high school with concession buildings, press box and full sports lighting.",
    description: [
      "Three-story 291,345 square foot school building, two concession buildings, a press box, site lighting, and sports lighting for one football field and two baseball fields.",
    ],
    square_feet: 291345,
    stories: 3,
    electrical_contract_value: 7800000,
    scope: ["Electrical", "Site Lighting", "Sports Lighting"],
    general_contractor: "Kraft Construction Company, Inc.",
    owner: "Lee County School Board",
    display_order: 30,
  },
  {
    legacy: "commercial-electrical-construction",
    slug: "ida-baker-high-school",
    name: "Ida Baker High School",
    status: "completed",
    category: "education",
    city: "Cape Coral",
    summary: "Two-story, 325,000 SF high school campus including gymnasium and auditorium.",
    description: [
      "Two-story, 325,000 square foot school campus including a 21,000 square foot indoor gymnasium and a 16,400 square foot auditorium.",
    ],
    square_feet: 325000,
    stories: 2,
    electrical_contract_value: 5700000,
    general_contractor: "Kraft Construction Company, Inc.",
    owner: "Lee County School Board",
    display_order: 31,
  },
  {
    legacy: "lee-county-justice-center-tower-addition",
    slug: "lee-county-justice-center-tower-addition",
    name: "Lee County Justice Center — Tower Addition",
    status: "completed",
    category: "government",
    city: "Fort Myers",
    summary: "Ten-story, 169,900 SF courthouse tower and a 56,300 SF parking garage.",
    description: [
      "Ten-story 169,900 square foot courthouse building and a 56,300 square foot parking garage.",
    ],
    square_feet: 169900,
    stories: 10,
    project_size: "+ 56,300 SF parking garage",
    electrical_contract_value: 4000000,
    general_contractor: "Balfour Beatty Construction",
    owner: "Lee County",
    display_order: 32,
  },
  {
    legacy: "gulf-coast-village-assisted-living-memory-support",
    slug: "gulf-coast-village-assisted-living-memory-support",
    name: "Gulf Coast Village Assisted Living & Memory Support",
    status: "completed",
    category: "senior-living",
    city: "Cape Coral",
    summary: "Three-story, 148,000 SF assisted living facility with memory support.",
    description: ["Three-story 148,000 square foot assisted living facility with memory support."],
    square_feet: 148000,
    stories: 3,
    electrical_contract_value: 3700000,
    general_contractor: "Lecessee Construction Services, LLC",
    owner: "Gulf Care, Inc.",
    display_order: 33,
  },
  {
    legacy: "thrive-at-naples-senior-living",
    slug: "thrive-at-naples-senior-living",
    name: "Thrive at Naples Senior Living",
    status: "completed",
    category: "senior-living",
    city: "Naples",
    summary: "Three-story, 189,000 SF assisted living facility.",
    description: ["Three-story 189,000 square foot assisted living facility."],
    square_feet: 189000,
    stories: 3,
    electrical_contract_value: 3500000,
    general_contractor: "DeAngelis Diamond Construction Company, Inc.",
    owner: "Fortress Ventures",
    display_order: 34,
  },
  {
    legacy: "lexington-middle-school",
    slug: "lexington-middle-school",
    name: "Lexington Middle School",
    status: "completed",
    category: "education",
    city: "Fort Myers",
    summary: "Three-story, 167,800 SF school building and a 24,200 SF gymnasium.",
    description: ["Three-story 167,800 square foot school building and a 24,200 square foot indoor gymnasium building."],
    square_feet: 167800,
    stories: 3,
    project_size: "+ 24,200 SF gymnasium",
    electrical_contract_value: 2735000,
    general_contractor: "DeAngelis Diamond Construction Company, Inc.",
    owner: "Lee County School Board",
    display_order: 35,
  },
  {
    legacy: "calusa-harbour",
    slug: "calusa-harbour",
    name: "Calusa Harbour",
    status: "completed",
    category: "senior-living",
    city: "Fort Myers",
    summary: "20-story senior living tower — multi-phase interior remodel and full switchgear replacement.",
    description: [
      "A multi-phase project in an occupied 20-story assisted living tower: remodeling all common areas, adding a bistro, and replacing every panelboard and switchboard throughout the building.",
    ],
    stories: 20,
    electrical_contract_value: 2000000,
    scope: ["Switchgear Replacement", "Panelboard Replacement", "Common Area Remodel"],
    general_contractor: "The Walker Group / Five Star Senior Living",
    owner: "Five Star Senior Living",
    display_order: 36,
  },
  {
    legacy: "fgcu-engineering-building-holmes-hall",
    slug: "fgcu-engineering-building-holmes-hall",
    name: "FGCU Engineering Building — Holmes Hall",
    status: "completed",
    category: "education",
    city: "Fort Myers",
    summary: "Four-story, 70,600 SF classroom and laboratory building.",
    description: ["Four-story 70,600 square foot classroom and lab building."],
    square_feet: 70600,
    stories: 4,
    electrical_contract_value: 2000000,
    general_contractor: "Kraft Construction Company, Inc.",
    owner: "Florida Gulf Coast University",
    display_order: 37,
  },
  {
    legacy: "baker-pre-k-center",
    slug: "baker-pre-k-center",
    name: "Baker Pre-K Center",
    status: "completed",
    category: "education",
    city: "Punta Gorda",
    summary: "New 51,280 SF childcare center built to LEED requirements.",
    description: ["New 51,280 square foot childcare center with site lighting, built to the latest LEED requirements."],
    square_feet: 51280,
    electrical_contract_value: 1900000,
    scope: ["Electrical", "Site Lighting"],
    general_contractor: "Balfour Beatty Construction",
    owner: "Charlotte County School Board",
    display_order: 38,
  },
  {
    legacy: "naples-jail-expansion-and-renovation",
    slug: "naples-jail-expansion-and-renovation",
    name: "Naples Jail Expansion & Renovation",
    status: "completed",
    category: "government",
    city: "Naples",
    summary: "Three-story, 91,000 SF addition and 19,200 SF renovation of the county jail.",
    description: ["Three-story 91,000 square foot addition and 19,200 square foot renovation of the county jail."],
    square_feet: 110200,
    stories: 3,
    project_size: "91,000 SF addition + 19,200 SF renovation",
    electrical_contract_value: 1700000,
    general_contractor: "Kraft Construction Company, Inc.",
    owner: "Collier County",
    display_order: 39,
  },
  {
    legacy: "sanibel-community-recreation-center",
    slug: "sanibel-community-recreation-center",
    name: "Sanibel Community Recreation Center",
    status: "completed",
    category: "community",
    city: "Sanibel",
    summary: "39,000 SF recreation center with gymnasium, pool, locker rooms and chiller yard.",
    description: ["39,000 square foot recreation center with gymnasium, multi-purpose room, pool, locker rooms, site lighting and chiller yard."],
    square_feet: 39000,
    electrical_contract_value: 950000,
    scope: ["Electrical", "Site Lighting"],
    general_contractor: "Peter Brown Construction Company, Inc.",
    owner: "City of Sanibel",
    display_order: 40,
  },
  {
    legacy: "south-seas-resort-phase-1-and-2",
    slug: "south-seas-resort-phase-1-and-2",
    name: "South Seas Resort — Phase 1 & 2",
    status: "completed",
    category: "hospitality",
    city: "Captiva",
    summary: "Complete electrical renovation of a 136-slip resort marina with two new 800A services.",
    description: ["Complete electrical renovation of a 136-slip marina, including telephone and TV cabling and two new 800 amp electrical services."],
    project_size: "136-slip marina",
    electrical_contract_value: 750000,
    scope: ["Marina Electrical Renovation", "Two 800A Electrical Services", "Telephone & TV Cabling"],
    general_contractor: "The Fishel Company",
    owner: "Meristar Hospitality Corporation",
    display_order: 41,
  },
  {
    legacy: "fort-myers-fire-station-no-1-and-administration",
    slug: "fort-myers-fire-station-no-1-and-administration",
    name: "Fort Myers Fire Station No. 1 & Administration",
    status: "completed",
    category: "government",
    city: "Fort Myers",
    summary: "Four-story, 32,800 SF fire station and administration building.",
    description: ["Four-story 32,800 square foot fire station and administration building."],
    square_feet: 32800,
    stories: 4,
    electrical_contract_value: 700000,
    general_contractor: "Gilbane Building Company",
    owner: "City of Fort Myers",
    display_order: 42,
  },
  {
    legacy: "la-z-boy-furniture",
    slug: "la-z-boy-furniture",
    name: "La-Z-Boy Furniture",
    status: "completed",
    category: "commercial",
    city: "Fort Myers",
    summary: "60,000 SF conversion of a former grocery store into a La-Z-Boy showroom and tenant space.",
    description: ["Renovation of an Albertson's grocery store into a La-Z-Boy furniture store with additional tenant fit-out space — 60,000 square feet total."],
    square_feet: 60000,
    electrical_contract_value: 650000,
    general_contractor: "Tri-Mar Construction",
    owner: "La-Z-Boy Furniture",
    display_order: 43,
  },
  {
    legacy: "somerset-clubhouse",
    slug: "somerset-clubhouse",
    name: "Somerset Clubhouse",
    status: "completed",
    category: "community",
    city: "Fort Myers",
    summary: "Two-story, 30,000 SF high-end clubhouse with cart barn and site lighting.",
    description: ["Two-story, 30,000 square foot high-end clubhouse with cart barn and site lighting."],
    square_feet: 30000,
    stories: 2,
    electrical_contract_value: 600000,
    scope: ["Electrical", "Site Lighting"],
    general_contractor: "Balfour Beatty Construction",
    owner: "Centex Homes",
    display_order: 44,
  },
  {
    legacy: "flagler-construction-equipment",
    slug: "flagler-construction-equipment",
    name: "Flagler Construction Equipment",
    status: "completed",
    category: "commercial",
    city: "Fort Myers",
    summary: "26,000 SF heavy equipment sales and maintenance facility.",
    description: ["26,000 square foot heavy equipment sales and maintenance facility."],
    square_feet: 26000,
    electrical_contract_value: 600000,
    general_contractor: "Peter Brown Construction Company, Inc.",
    owner: "Flagler Construction Equipment",
    display_order: 45,
  },
  {
    legacy: "summit-church",
    slug: "summit-church",
    name: "Summit Church",
    status: "completed",
    category: "community",
    city: "Fort Myers",
    summary: "26,640 SF sanctuary, offices and meeting rooms with site lighting.",
    description: ["26,640 square foot new sanctuary, offices, meeting rooms and site lighting."],
    square_feet: 26640,
    electrical_contract_value: 550000,
    scope: ["Electrical", "Site Lighting"],
    general_contractor: "DeAngelis Diamond Construction Company, Inc.",
    owner: "Summit Church",
    display_order: 46,
  },
  {
    legacy: "ron-jon-surf-shop-fort-myers",
    slug: "ron-jon-surf-shop-fort-myers",
    name: "Ron Jon Surf Shop — Fort Myers",
    status: "completed",
    category: "commercial",
    city: "Fort Myers",
    summary: "12,500 SF tenant fit-out at Gulf Coast Town Center.",
    description: ["12,500 square foot tenant fit-out for Ron Jon Surf Shop at Gulf Coast Town Center."],
    square_feet: 12500,
    electrical_contract_value: 325000,
    general_contractor: "Tri-Mar Construction",
    owner: "Ron Jon Surf Shop",
    display_order: 47,
  },
  {
    legacy: "riverside-park-phase-1",
    slug: "riverside-park-phase-1",
    name: "Riverside Park — Phase 1",
    status: "completed",
    category: "community",
    city: "Bonita Springs",
    summary: "New band shell and site lighting across a city block of park land.",
    description: ["New 2,000 square foot band shell and site lighting on one city block of park land."],
    square_feet: 2000,
    electrical_contract_value: 300000,
    scope: ["Electrical", "Site Lighting"],
    general_contractor: "Centex Construction, LLC",
    owner: "City of Bonita Springs",
    display_order: 48,
  },
  {
    legacy: "treviso-bay",
    slug: "treviso-bay",
    name: "Treviso Bay",
    status: "completed",
    category: "commercial",
    city: "Naples",
    summary: "Community entry bridge, towers and guard house.",
    description: ["Project consisted of the entry bridge and towers and a guard house."],
    electrical_contract_value: 200000,
    general_contractor: "Kraft Construction Company, Inc.",
    owner: "Treviso Bay Development, LLC",
    display_order: 49,
  },
  {
    legacy: "crown-of-life-church",
    slug: "crown-of-life-church",
    name: "Crown of Life Church",
    status: "completed",
    category: "community",
    city: "Fort Myers",
    summary: "17,500 SF fellowship hall with site lighting.",
    description: ["17,500 square foot fellowship hall and site lighting."],
    square_feet: 17500,
    electrical_contract_value: 155000,
    scope: ["Electrical", "Site Lighting"],
    general_contractor: "DeAngelis Diamond Construction Company, Inc.",
    owner: "Crown of Life Church",
    display_order: 50,
  },
  {
    legacy: "venetian-plaza-building-d",
    slug: "venetian-plaza-building-d",
    name: "Venetian Plaza Building D",
    status: "completed",
    category: "commercial",
    city: "Naples",
    summary: "Two-story, 17,200 SF shell office building.",
    description: ["Two-story 17,200 square foot shell office building."],
    square_feet: 17200,
    stories: 2,
    electrical_contract_value: 123000,
    general_contractor: "Kraft Construction Company, Inc.",
    owner: "Armalavage & Associates",
    display_order: 51,
  },
  {
    legacy: "bigham-galleries",
    slug: "bigham-galleries",
    name: "Bigham Galleries",
    status: "completed",
    category: "commercial",
    city: "Naples",
    summary: "Second-floor tenant improvements for multiple office tenants.",
    description: ["Second-floor tenant improvements: a 2,300 square foot fit-out, a 3,500 square foot fit-out for Dee CPA and an 800 square foot fit-out for Dr. Labs."],
    square_feet: 6600,
    electrical_contract_value: 110000,
    general_contractor: "DeAngelis Diamond Construction Company, Inc.",
    owner: "BJI Development LLC, Winndepeg Way LLC, PCL Management",
    display_order: 52,
  },
  {
    legacy: "boardwalk-caper-marina",
    slug: "boardwalk-caper-marina",
    name: "Boardwalk Caper Marina",
    status: "completed",
    category: "hospitality",
    city: "Fort Myers",
    summary: "Complete electrical renovation and service upgrade of a 96-slip marina.",
    description: ["Complete electrical renovation and service upgrade of a 96-slip marina, self-performed by Fortune Electrical as GC."],
    project_size: "96-slip marina",
    electrical_contract_value: 75000,
    scope: ["Marina Electrical Renovation", "Service Upgrade"],
    general_contractor: "Fortune Electrical Construction",
    owner: "Suitor & Associates",
    display_order: 53,
  },
  {
    legacy: "emergency-generator-projects",
    slug: "emergency-generator-projects",
    name: "Emergency Generator Program — State of Florida",
    status: "completed",
    category: "power",
    location_label: "Statewide, FL",
    summary: "Turnkey emergency generator and transfer switch installations at schools across Florida.",
    description: [
      "Turnkey emergency generator installations — including new fenced compounds or new buildings where required — with transfer switches serving any portion of a facility, or the entire facility.",
      "The generators shown were installed for the State of Florida Department of Management Services at various schools throughout the state. The construction manager was a joint venture between Trane Orlando and KBR.",
    ],
    scope: ["Emergency Generators", "Transfer Switches", "Generator Compounds"],
    general_contractor: "Trane Orlando / KBR (JV)",
    owner: "State of Florida Department of Management Services",
    display_order: 54,
  },
  {
    legacy: "5-5-kw-solar-photovoltaic-pv-installation",
    slug: "solar-pv-installation-5-5-kw",
    name: "5.5 kW Solar PV Installation",
    status: "completed",
    category: "power",
    city: "Fort Myers",
    summary: "Design-build solar PV system: 24 × 230 W modules with an SMA Sunny Boy inverter.",
    description: ["A 5.5 kW solar PV system with 24 – 230 W modules and an SMA Sunny Boy 5000US inverter, designed and built by Fortune Electrical."],
    electrical_contract_value: 30000,
    scope: ["Design-Build", "Solar PV"],
    display_order: 55,
  },
];

// Listed as logos under "Current Projects" on the legacy site but with no
// project entry. Imported as UNPUBLISHED drafts so Fortune can complete them.
export const draftCurrent = [
  { slug: "gulfshore-playhouse", name: "Gulfshore Playhouse", category: "community" },
  { slug: "olde-naples-hotel", name: "Olde Naples Hotel", category: "hospitality" },
  { slug: "arthrex", name: "Arthrex", category: "commercial" },
];

export const statistics = [
  { label: "Years Serving Florida", value: 20, suffix: "+", auto_source: "manual", sort_order: 1, is_active: true },
  { label: "Projects in Portfolio", auto_source: "project_count", sort_order: 2, is_active: true },
  { label: "Square Feet Delivered", auto_source: "square_feet", compact: true, suffix: "+", sort_order: 3, is_active: true, description: "Sum of square footage across published projects" },
  { label: "Residential Units", auto_source: "units", suffix: "+", sort_order: 4, is_active: true, description: "Sum of units across published projects" },
  // Fortune to supply — hidden until a value is entered
  { label: "Project Volume", prefix: "$", compact: true, suffix: "+", auto_source: "manual", sort_order: 5, is_active: false },
  { label: "Employees", auto_source: "manual", suffix: "+", sort_order: 6, is_active: false },
];

export const capabilities = [
  { title: "Commercial Electrical Construction", body: "Ground-up and renovation: utility coordination, site service, power distribution, grounding and bonding." },
  { title: "Power Distribution & Switchgear", body: "Three-phase service, switchgear and panelboards, service upgrades for heavy equipment and HVAC loads." },
  { title: "Emergency & Standby Power", body: "Generators, transfer switches and emergency power pathways for mission-critical facilities." },
  { title: "Lighting", body: "Interior, exterior, site and sports lighting, controls, emergency and exit lighting." },
  { title: "Fire Alarm", body: "Design, installation, retrofits, testing, inspection and 24/7 monitoring." },
  { title: "Low Voltage & Communications", body: "Structured cabling, fiber, access control, CCTV, ERRCS/BDA and intercom systems." },
  { title: "Multifamily", body: "Garden, podium and wrap communities, student housing and senior living — 50 to 500+ units." },
  { title: "Specialty Projects", body: "A dedicated division for tenant improvements, buildouts and fast-moving small commercial work." },
];
